define(function(){
return{
	Manifest : [
		{src:"img/canvas/abijity_eff_13.png", id:"abijity_eff_13"},
		{src:"img/canvas/abijity_eff_14.png", id:"abijity_eff_14"},
		{src:"img/canvas/abijity_eff_15.png", id:"abijity_eff_15"},
		{src:"img/canvas/abijity_eff_16.png", id:"abijity_eff_16"},
		{src:"img/canvas/attack_bg_01.png", id:"attack_bg_01"},
		{src:"img/canvas/attack_id31001_massage.png", id:"attack_id31001_massage"},
		{src:"img/canvas/combo_eff_01.png", id:"combo_eff_01"},
		{src:"img/canvas/combo_eff_02.png", id:"combo_eff_02"},
		{src:"img/canvas/combo_member_1.png", id:"combo_member_1"},
		{src:"img/canvas/combo_member_2.png", id:"combo_member_2"},
		{src:"img/canvas/combo_member_3.png", id:"combo_member_3"},
		{src:"img/canvas/common_eff_01.png", id:"common_eff_01"},
		{src:"img/canvas/common_eff_03.png", id:"common_eff_03"},
		{src:"img/canvas/common_eff_05.png", id:"common_eff_05"},
		{src:"img/canvas/common_eff_07.png", id:"common_eff_07"},
		{src:"img/canvas/enemy_01.png", id:"enemy_01"},
		{src:"img/canvas/enemy_09.png", id:"enemy_09"},
		{src:"img/canvas/id31001_01.png", id:"id31001_01"},
		{src:"img/canvas/id31001_04.png", id:"id31001_04"},
		{src:"img/canvas/id31001_05.png", id:"id31001_05"},
		{src:"img/canvas/id31001_rod.png", id:"id31001_rod"},
		{src:"img/canvas/number_combo_00.png", id:"number_combo_00"},
		{src:"img/canvas/number_combo_01.png", id:"number_combo_01"},
		{src:"img/canvas/number_combo_02.png", id:"number_combo_02"},
		{src:"img/canvas/number_combo_03.png", id:"number_combo_03"},
		{src:"img/canvas/number_combo_04.png", id:"number_combo_04"},
		{src:"img/canvas/number_combo_05.png", id:"number_combo_05"},
		{src:"img/canvas/number_combo_06.png", id:"number_combo_06"},
		{src:"img/canvas/number_combo_07.png", id:"number_combo_07"},
		{src:"img/canvas/number_combo_08.png", id:"number_combo_08"},
		{src:"img/canvas/number_combo_09.png", id:"number_combo_09"},
		{src:"img/canvas/number_combo_moji.png", id:"number_combo_moji"},
		{src:"img/canvas/number_damage_0.png", id:"number_damage_0"},
		{src:"img/canvas/number_damage_1.png", id:"number_damage_1"},
		{src:"img/canvas/number_damage_2.png", id:"number_damage_2"},
		{src:"img/canvas/number_damage_3.png", id:"number_damage_3"},
		{src:"img/canvas/number_damage_4.png", id:"number_damage_4"},
		{src:"img/canvas/number_damage_5.png", id:"number_damage_5"},
		{src:"img/canvas/number_damage_6.png", id:"number_damage_6"},
		{src:"img/canvas/number_damage_7.png", id:"number_damage_7"},
		{src:"img/canvas/number_damage_8.png", id:"number_damage_8"},
		{src:"img/canvas/number_damage_9.png", id:"number_damage_9"}
	],
	Element : '<canvas id="canvas" width="320" height="200" style="background-color:#ffffff"></canvas>'
}
});