define(function(){
return{
	Manifest : [
		{src:"img/canvas/gacha_box02_01.png", id:"gacha_box02_01"},
		{src:"img/canvas/gacha_box02_02.png", id:"gacha_box02_02"},
		{src:"img/canvas/gacha_box02_03.png", id:"gacha_box02_03"},
		{src:"img/canvas/gacha_box02_04.png", id:"gacha_box02_04"},
		{src:"img/canvas/gacha_box02_05.png", id:"gacha_box02_05"},
		{src:"img/canvas/gacha_event__eff_yellow_01.png", id:"gacha_event__eff_yellow_01"},
		{src:"img/canvas/gacha_event_201305.png", id:"gacha_event_201305"},
		{src:"img/canvas/gacha_event_3nin.png", id:"gacha_event_3nin"},
		{src:"img/canvas/gacha_event_apush_01.png", id:"gacha_event_apush_01"},
		{src:"img/canvas/gacha_event_bg_eff_01.png", id:"gacha_event_bg_eff_01"},
		{src:"img/canvas/gacha_event_box_shadow.png", id:"gacha_event_box_shadow"},
		{src:"img/canvas/gacha_event_carnation1.png", id:"gacha_event_carnation1"},
		{src:"img/canvas/gacha_event_carnation2.png", id:"gacha_event_carnation2"},
		{src:"img/canvas/gacha_event_compo_eff_01.png", id:"gacha_event_compo_eff_01"},
		{src:"img/canvas/gacha_event_eff_sen1.png", id:"gacha_event_eff_sen1"},
		{src:"img/canvas/gacha_event_eff_sen2.png", id:"gacha_event_eff_sen2"},
		{src:"img/canvas/gacha_event_eff_sen3.png", id:"gacha_event_eff_sen3"},
		{src:"img/canvas/gacha_event_eff_sen4.png", id:"gacha_event_eff_sen4"},
		{src:"img/canvas/gacha_event_eff_sen5.png", id:"gacha_event_eff_sen5"},
		{src:"img/canvas/gacha_event_eff_yellow_02.png", id:"gacha_event_eff_yellow_02"},
		{src:"img/canvas/gacha_event_eff_yellow_03.png", id:"gacha_event_eff_yellow_03"},
		{src:"img/canvas/gacha_event_enb1.png", id:"gacha_event_enb1"},
		{src:"img/canvas/gacha_event_enb2.png", id:"gacha_event_enb2"},
		{src:"img/canvas/gacha_event_enb3.png", id:"gacha_event_enb3"},
		{src:"img/canvas/gacha_event_gacha_bg_04.png", id:"gacha_event_gacha_bg_04"},
		{src:"img/canvas/gacha_event_gacha_cha_02.png", id:"gacha_event_gacha_cha_02"},
		{src:"img/canvas/gacha_event_gacha_eff_flash_01.png", id:"gacha_event_gacha_eff_flash_01"},
		{src:"img/canvas/gacha_event_gacha_eff_flash_02.png", id:"gacha_event_gacha_eff_flash_02"},
		{src:"img/canvas/gacha_event_gacha_eff_flash_03.png", id:"gacha_event_gacha_eff_flash_03"},
		{src:"img/canvas/gacha_event_items_13_gacha.png", id:"gacha_event_items_13_gacha"},
		{src:"img/canvas/gacha_event_mozi1.png", id:"gacha_event_mozi1"},
		{src:"img/canvas/gacha_event_mozi10.png", id:"gacha_event_mozi10"},
		{src:"img/canvas/gacha_event_mozi2.png", id:"gacha_event_mozi2"},
		{src:"img/canvas/gacha_event_mozi3.png", id:"gacha_event_mozi3"},
		{src:"img/canvas/gacha_event_mozi4.png", id:"gacha_event_mozi4"},
		{src:"img/canvas/gacha_event_mozi5.png", id:"gacha_event_mozi5"},
		{src:"img/canvas/gacha_event_mozi6.png", id:"gacha_event_mozi6"},
		{src:"img/canvas/gacha_event_mozi7.png", id:"gacha_event_mozi7"},
		{src:"img/canvas/gacha_event_mozi8.png", id:"gacha_event_mozi8"},
		{src:"img/canvas/gacha_event_mozi9.png", id:"gacha_event_mozi9"},
		{src:"img/canvas/gacha_event_ransa1.png", id:"gacha_event_ransa1"},
		{src:"img/canvas/gacha_event_ransa2.png", id:"gacha_event_ransa2"},
		{src:"img/canvas/gacha_event_rare_massage_02.png", id:"gacha_event_rare_massage_02"},
		{src:"img/canvas/gacha_event_samurai1.png", id:"gacha_event_samurai1"},
		{src:"img/canvas/gacha_event_samurai2.png", id:"gacha_event_samurai2"},
		{src:"img/canvas/gacha_event_sikiri.png", id:"gacha_event_sikiri"}
	],
	Element : '<canvas id="canvas" width="320" height="320" style="background-color:#ffffff"></canvas>'
}
});