define(function(){
return{
	Manifest : [
		{src:"img/canvas/attack_0_01.png", id:"attack_0_01"},
		{src:"img/canvas/attack_0_09.png", id:"attack_0_09"},
		{src:"img/canvas/attack_1_01.png", id:"attack_1_01"},
		{src:"img/canvas/attack_1_09.png", id:"attack_1_09"},
		{src:"img/canvas/attack_2_01.png", id:"attack_2_01"},
		{src:"img/canvas/attack_2_09.png", id:"attack_2_09"},
		{src:"img/canvas/attack_3_01.png", id:"attack_3_01"},
		{src:"img/canvas/attack_3_09.png", id:"attack_3_09"},
		{src:"img/canvas/attack_4_01.png", id:"attack_4_01"},
		{src:"img/canvas/attack_4_09.png", id:"attack_4_09"},
		{src:"img/canvas/attack_bg_01.png", id:"attack_bg_01"},
		{src:"img/canvas/combo_eff_01.png", id:"combo_eff_01"},
		{src:"img/canvas/combo_eff_02.png", id:"combo_eff_02"},
		{src:"img/canvas/combo_member_1.png", id:"combo_member_1"},
		{src:"img/canvas/combo_member_2.png", id:"combo_member_2"},
		{src:"img/canvas/combo_member_3.png", id:"combo_member_3"},
		{src:"img/canvas/common_eff_02.png", id:"common_eff_02"},
		{src:"img/canvas/common_eff_03.png", id:"common_eff_03"},
		{src:"img/canvas/common_eff_06.png", id:"common_eff_06"},
		{src:"img/canvas/common_eff_07.png", id:"common_eff_07"},
		{src:"img/canvas/me_01.png", id:"me_01"},
		{src:"img/canvas/me_02.png", id:"me_02"},
		{src:"img/canvas/me_04.png", id:"me_04"},
		{src:"img/canvas/me_08.png", id:"me_08"},
		{src:"img/canvas/number_combo_00.png", id:"number_combo_00"},
		{src:"img/canvas/number_combo_01.png", id:"number_combo_01"},
		{src:"img/canvas/number_combo_02.png", id:"number_combo_02"},
		{src:"img/canvas/number_combo_03.png", id:"number_combo_03"},
		{src:"img/canvas/number_combo_04.png", id:"number_combo_04"},
		{src:"img/canvas/number_combo_05.png", id:"number_combo_05"},
		{src:"img/canvas/number_combo_06.png", id:"number_combo_06"},
		{src:"img/canvas/number_combo_07.png", id:"number_combo_07"},
		{src:"img/canvas/number_combo_08.png", id:"number_combo_08"},
		{src:"img/canvas/number_combo_09.png", id:"number_combo_09"},
		{src:"img/canvas/number_combo_moji.png", id:"number_combo_moji"},
		{src:"img/canvas/yell_eff_yellow_04.png", id:"yell_eff_yellow_04"},
		{src:"img/canvas/yell_eff_yellow_05.png", id:"yell_eff_yellow_05"},
		{src:"img/canvas/yell_magicguarddown_01.png", id:"yell_magicguarddown_01"},
		{src:"img/canvas/yell_magicguarddown_02.png", id:"yell_magicguarddown_02"},
		{src:"img/canvas/yell_magicguarddown_03.png", id:"yell_magicguarddown_03"},
		{src:"img/canvas/yell_magicguarddown_04.png", id:"yell_magicguarddown_04"},
		{src:"img/canvas/yell_magicguarddown_05.png", id:"yell_magicguarddown_05"},
		{src:"img/canvas/yell_magicguarddown_06.png", id:"yell_magicguarddown_06"},
		{src:"img/canvas/yell_massage_05.png", id:"yell_massage_05"}
	],
	Element : '<canvas id="canvas" width="320" height="200" style="background-color:#ffffff"></canvas>'
}
});