define(function(){
return{
	Manifest : [
		{src:"img/canvas/attack_bg_01.png", id:"attack_bg_01"},
		{src:"img/canvas/combo_eff_01.png", id:"combo_eff_01"},
		{src:"img/canvas/combo_eff_02.png", id:"combo_eff_02"},
		{src:"img/canvas/combo_member_1.png", id:"combo_member_1"},
		{src:"img/canvas/combo_member_2.png", id:"combo_member_2"},
		{src:"img/canvas/combo_member_3.png", id:"combo_member_3"},
		{src:"img/canvas/common_eff_03.png", id:"common_eff_03"},
		{src:"img/canvas/common_eff_06.png", id:"common_eff_06"},
		{src:"img/canvas/common_eff_07.png", id:"common_eff_07"},
		{src:"img/canvas/common_eff_09.png", id:"common_eff_09"},
		{src:"img/canvas/me_01.png", id:"me_01"},
		{src:"img/canvas/me_02.png", id:"me_02"},
		{src:"img/canvas/me_04.png", id:"me_04"},
		{src:"img/canvas/me_08.png", id:"me_08"},
		{src:"img/canvas/number_combo_00.png", id:"number_combo_00"},
		{src:"img/canvas/number_combo_01.png", id:"number_combo_01"},
		{src:"img/canvas/number_combo_02.png", id:"number_combo_02"},
		{src:"img/canvas/number_combo_03.png", id:"number_combo_03"},
		{src:"img/canvas/number_combo_04.png", id:"number_combo_04"},
		{src:"img/canvas/number_combo_05.png", id:"number_combo_05"},
		{src:"img/canvas/number_combo_06.png", id:"number_combo_06"},
		{src:"img/canvas/number_combo_07.png", id:"number_combo_07"},
		{src:"img/canvas/number_combo_08.png", id:"number_combo_08"},
		{src:"img/canvas/number_combo_09.png", id:"number_combo_09"},
		{src:"img/canvas/number_combo_moji.png", id:"number_combo_moji"},
		{src:"img/canvas/target_01.png", id:"target_01"},
		{src:"img/canvas/target_02.png", id:"target_02"},
		{src:"img/canvas/target_04.png", id:"target_04"},
		{src:"img/canvas/yell_eff_green_01.png", id:"yell_eff_green_01"},
		{src:"img/canvas/yell_eff_green_02.png", id:"yell_eff_green_02"},
		{src:"img/canvas/yell_eff_green_03.png", id:"yell_eff_green_03"},
		{src:"img/canvas/yell_eff_green_04.png", id:"yell_eff_green_04"},
		{src:"img/canvas/yell_eff_green_05.png", id:"yell_eff_green_05"},
		{src:"img/canvas/yell_magicup_01.png", id:"yell_magicup_01"},
		{src:"img/canvas/yell_magicup_02.png", id:"yell_magicup_02"},
		{src:"img/canvas/yell_magicup_03.png", id:"yell_magicup_03"},
		{src:"img/canvas/yell_magicup_04.png", id:"yell_magicup_04"},
		{src:"img/canvas/yell_magicup_05.png", id:"yell_magicup_05"},
		{src:"img/canvas/yell_massage_01.png", id:"yell_massage_01"}
	],
	Element : '<canvas id="canvas" width="320" height="200" style="background-color:#ffffff"></canvas>'
}
});